CREATE TABLE person
(
    person_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      varchar(100)         not null,
    age       int check ( age > 5) not null
);

CREATE TABLE book
(
    book_id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title            varchar(100)             not null,
    author           varchar(100)             not null,
    year             int check ( year > 1900) not null,
    person_id        int                      references person (person_id) on delete set null,
    assignation_date date
);


INSERT INTO person(name, age)
VALUES ('Stanislav Ermolenko', 18);
INSERT INTO person(name, age)
VALUES ('Vyacheslav Stoev', 20);
INSERT INTO person(name, age)
VALUES ('Igor Nikolaev', 12);
INSERT INTO person(name, age)
VALUES ('Alexey Bershev', 15);
INSERT INTO person(name, age)
VALUES ('Nikita Shtanyko', 7);


INSERT INTO book(title, author, year)
VALUES ('To Kill a Mockingbird', 'Harper Lee', 1990);
INSERT INTO book(title, author, year)
VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1999);
INSERT INTO book(title, author, year)
VALUES ('1984', 'George Orwell', 2000);
INSERT INTO book(title, author, year)
VALUES ('The Lord Of Rings', 'J.R.R. Tolkien', 1995);
INSERT INTO book(title, author, year)
VALUES ('Stalker', 'Sergey Basil', 2005);
INSERT INTO book(title, author, year)
VALUES ('One Hundred Years Of Solitude', 'Gabriel Garcia Marquez', 1985);
INSERT INTO book(title, author, year)
VALUES ('The Bell Jar', 'Sylvia Plath', 1946);